[package]
name = "netease-cloud-music-gtk4"
version = "2.3.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "~0.7", features = ["gettext-system"] }
gtk = { version = "~0.7", package = "gtk4" }
once_cell = "~1.18"
qrcode-generator = "~4.1"
# ncm-api = { git = "https://github.com/gmg137/netease-cloud-music-api.git", branch = "dev", package = "netease-cloud-music-api" }
ncm-api = { git = "https://gitee.com/gmg137/netease-cloud-music-api.git", tag = "1.3.0", package = "netease-cloud-music-api" }
anyhow = "~1.0"
gstreamer = "~0.21"
gstreamer-play = "~0.21"
fastrand = "~2.0"
mpris-server = "~0.6.0"
regex = "~1.10"
log = "~0.4"
env_logger = "~0.10"
cookie_store = "~0.20"
chrono = "~0.4"

[dependencies.adw]
package = "libadwaita"
version = "~0.5"
