[package]
name = "netease-cloud-music-gtk4"
version = "2.3.1"
edition = "2021"

[dependencies]
gettext-rs = { version = "~0.7", features = ["gettext-system"] }
gtk = { version = "~0.8", package = "gtk4" }
once_cell = "~1.19"
qrcode-generator = "~4.1"
# ncm-api = { git = "https://github.com/gmg137/netease-cloud-music-api.git", branch = "dev", package = "netease-cloud-music-api" }
ncm-api = { git = "https://gitee.com/gmg137/netease-cloud-music-api.git", tag = "1.3.1", package = "netease-cloud-music-api" }
anyhow = "~1.0"
gstreamer = "~0.22"
gstreamer-play = "~0.22"
fastrand = "~2.0"
mpris-server = "~0.7.0"
regex = "~1.10"
log = "~0.4"
env_logger = "~0.11"
cookie_store = "~0.21"
chrono = "~0.4"
async-channel = "~2.2"

[dependencies.adw]
package = "libadwaita"
version = "~0.6"
